---
# Nested vSphere deployment starts here
- import_playbook: playbooks/preparePhysical.yml
- import_playbook: playbooks/deployRouter.yml
- import_playbook: playbooks/deployVc.yml
- import_playbook: playbooks/prepareISOInstaller.yml
- import_playbook: playbooks/deployNestedEsxi.yml

- name: Wait 5 minutes for the ESXi hosts to become fully responsive
  hosts: localhost
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Wait 5 minutes before checking whether the hosts are ready
      pause: minutes=5
      when: vESX|length > 5

- import_playbook: playbooks/configureNestedEsxi.yml
- import_playbook: playbooks/createVds.yml
- import_playbook: playbooks/configureVsan.yml
# Nested vSphere deployment ends here

# NSX-T deployment starts here
- import_playbook: playbooks/deployNsxManager.yml
- import_playbook: playbooks/addNsxLicense.yml
- import_playbook: playbooks/registerNsxComputeManager.yml
- import_playbook: playbooks/createNsxTz.yml
- import_playbook: playbooks/createNsxIpPool.yml
- import_playbook: playbooks/createNsxUplinkProfiles.yml
- import_playbook: playbooks/createNsxTnp.yml
- import_playbook: playbooks/attachNsxTnp.yml
- import_playbook: playbooks/createNsxEdgeTn.yml
- import_playbook: playbooks/createNsxEdgeCluster.yml
# NSX-T deployment ends here

- name: Wait 5 minutes for the NSX-T platform to become fully responsive
  hosts: localhost
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Wait 5 minutes before checking whether the NSX-T platform is ready
      pause: minutes=5
      when: 
        - deploy_nsxt == true
        - deploy_nsxt_edge == true

# NSX-T logical network provisioning starts here
- import_playbook: playbooks/createNsxSegments.yml
- import_playbook: playbooks/createNsxT0gateway.yml
# NSX-T logical network provisioning ends here
