## Rutger has ownership of this file for the v2 migration ##
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ./answerfile.yml
    - ./config.yml
    - ./software.yml
  tasks:

    - name: Remove VyOS router VM
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_Router.Name }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Remove ESXi VMs
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ item.value.VMName }}"
        force: true
        state: absent
      async: 7200
      poll: 0     
      loop: "{{ Nested_ESXi.Hosts | dict2items }}"
      ignore_errors: true

    - name: Remove vCenter VM
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_vCenter.VMName }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Remove NSX Manager VM(s)
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_NSXT.Components.LocalManager.VMName }}"
        force: true
        state: absent       
      ignore_errors: true

    - name: Remove trunk port group for the nested environment
      vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False        
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.Trunk.Name }}"
        state: absent
      ignore_errors: true

    - name: Remove management port group for the nested environment
      vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False        
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.Management.Name }}"
        state: absent
      ignore_errors: true

    - name: Remove VMware vSwitch on the ESXi host for the nested environment
      vmware_vswitch:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        state: absent
      async: 7200
      poll: 0
      ignore_errors: true

    - name: Remove static route on the Ansible control node
      command: ./ip route del "{{ pod_network }}.{{ pod + management }}.0/24"
      args:
        chdir: /bin/
      register: iproute
      ignore_errors: true
      when: 
        - deploy_router == true
        - router.protocol == "static"

    - name: Delete the Pod documentation
      file: 
        path: "/home/$SUDO_USER/pod-{{ pod }}-doc.html"
        state: absent
      when: 
        - DEBUG_keep_config_files != true

