# NSX-T Edge Transport Nodes
edge_transport_nodes:
- display_name: "{{ edge_node1 }}"
  host_switches:
  - host_switch_profiles:
    - name: edge-uplink-profile
      type: UplinkHostSwitchProfile
    host_switch_name: "{{ nvds_name }}"
    pnics:
    - device_name: "fp-eth0"
      uplink_name: "uplink-1"
    - device_name: "fp-eth1"
      uplink_name: "uplink-2"      
    ip_assignment_spec:
      resource_type: StaticIpListSpec
      ip_list:
      - "{{ transport_prefix }}.61"
      - "{{ transport_prefix }}.62"
      subnet_mask: "{{ transport_network_mask }}"
      default_gateway: "{{ transport_gw }}"
  node_deployment_info:
    resource_type: "EdgeNode"
    display_name: "{{ edge_node1 }}"
    ip_addresses:
    deployment_config:
      form_factor: "SMALL"
      node_user_settings:
        cli_password: "{{ edgepassword }}"
        root_password: "{{ edgepassword }}"
      vm_deployment_config:
        placement_type: VsphereDeploymentConfig
        vc_name: "{{ vcenter.fqdn }}"
        vc_username: "{{ vcenter.user }}"
        vc_password: "{{ vcenter.password }}"        
        data_networks:
        - "{{ vds.uplink1_pg }}"
        - "{{ vds.uplink2_pg }}"
        management_network: "{{ vds.management_pg }}"
        management_port_subnets:
        - ip_addresses:
          - "{{ mgmt_prefix }}.61"
          prefix_length: 24
        default_gateway_addresses: 
        - "{{ mgmt_network_gw }}"
        hostname: "{{ edge_node1 }}.{{ domain }}"
        compute: "{{ edge_node_vsphere_cluster }}"
        storage: "{{ nfs_datastore }}"
        host: "{{ edge_node1_vesxi }}"
- display_name: "{{ edge_node2 }}"
  host_switches:
  - host_switch_profiles:
    - name: edge-uplink-profile
      type: UplinkHostSwitchProfile
    host_switch_name: "{{ nvds_name }}"
    pnics:
    - device_name: "fp-eth0"
      uplink_name: "uplink-1"
    - device_name: "fp-eth1"
      uplink_name: "uplink-2"      
    ip_assignment_spec:
      resource_type: StaticIpListSpec
      ip_list:
      - "{{ transport_prefix }}.63"
      - "{{ transport_prefix }}.64"
      subnet_mask: "{{ transport_network_mask }}"
      default_gateway: "{{ transport_gw }}"
  node_deployment_info:
    resource_type: "EdgeNode"
    display_name: "{{ edge_node2 }}"
    ip_addresses:
    deployment_config:
      form_factor: "SMALL"
      node_user_settings:
        cli_password: "{{ edgepassword }}"
        root_password: "{{ edgepassword }}"
      vm_deployment_config:
        placement_type: VsphereDeploymentConfig
        vc_name: "{{ vcenter.fqdn }}"
        vc_username: "{{ vcenter.user }}"
        vc_password: "{{ vcenter.password }}"
        data_networks:
        - "{{ vds.uplink1_pg }}"
        - "{{ vds.uplink2_pg }}"
        management_network: "{{ vds.management_pg }}"
        management_port_subnets: 
        - ip_addresses:
          - "{{ mgmt_prefix }}.62"
          prefix_length: 24
        default_gateway_addresses: 
        - "{{ mgmt_network_gw }}"
        hostname: "{{ edge_node2 }}.{{ domain }}"
        compute: "{{ edge_node_vsphere_cluster }}"
        storage: "{{ nfs_datastore }}"
        host: "{{ edge_node2_vesxi }}"

# NSX-T Transport Node Profile
transport_node_profiles:
- display_name: "{{ tn_profile_name }}"
  host_switches:
  - host_switch_profiles:
    - name: esxi-uplink-profile
      type: UplinkHostSwitchProfile
    - name: LLDP [Send Packet Enabled]
      type: LldpHostSwitchProfile
    - name: nsx-default-nioc-hostswitch-profile
      type: NiocProfile
    host_switch_name: "{{ nvds_name }}"
    pnics:
    - device_name: vmnic3
      uplink_name: "uplink-1"
    - device_name: vmnic4
      uplink_name: "uplink-2"      
    ip_assignment_spec:
      resource_type: StaticIpPoolSpec
      ip_pool_name: "{{ ip_pool_name }}"