---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  vars:
    nsxlicensekey: "{{ lookup('file', '{{ nsxlicense }}') }}"
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if the NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey
      when: deploy_nsxt == true

    - name: Add NSX-T license
      nsxt_licenses:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        license_key: "{{ nsxlicensekey }}"
        state: "present"
      when: 
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true
