---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local 
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey
      when: deploy_nsxt == true

    - name: Conditionally load variables for NSX-T 2.5
      include_vars:
        file: nsxt25.yml
      when: 
        - nsxt_major_version == 2
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true

    - name: Conditionally load variables for NSX-T 3.0
      include_vars:
        file: nsxt30.yml
      when:
        - nsxt_major_version == 2
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true
      
    - name: Attach NSX-T transport node profile to vSphere cluster
      nsxt_transport_node_collections:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "TNC"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections"
        compute_manager_name: "{{ vcenter.fqdn }}"
        cluster_name: "Compute"
        transport_node_profile_name: "{{ transport_node_profiles.display_name }}"
        state: present
      when: 
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true
