---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Enable vSAN
      vmware_cluster_vsan:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: false
        cluster_name: "{{ item.key }}"
        enable_vsan: "{{ item.value.vsan }}"
        vsan_auto_claim_storage: false
      with_dict: "{{ clusters }}"
