## Rutger has ownership of this file for the v2 migration ##
##
## ToDo:     Not started
##
##
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../config.yml
    - ../answerfile.yml
  tasks:

    - name: Create Ruby script for silencing vSAN warnings
      template: 
        src=../templates/vsan_silence.rb.j2
        dest={{ Target.TempFolder }}/{{ item.key }}
      loop: "{{ Nested_Clusters | dict2items }}"
      when: item.value.vSAN|bool

    - name: Copy Ruby script to the nested vCenter deployed on the ESXi host
      vmware_guest_file_operation:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_vCenter.VMName }}"
        vm_username: "root"
        vm_password: "{{ Nested_vCenter.Password }}"
        copy:
            src: "{{ Target.TempFolder }}/{{ item.key }}"
            dest: "{{ Target.TempFolder }}/{{ item.key }}"
            overwrite: true
      loop: "{{ Nested_Clusters | dict2items }}"
      when: item.value.vSAN|bool
        
    - name: Run Ruby script
      vmware_vm_shell:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: false
        vm_id: "{{ vcenter.vmname }}"
        vm_username: "root"
        vm_password: "{{ vcenter.password }}"
        vm_shell: /usr/bin/rvc
        vm_shell_args: '{{ vcenter.user }}:VMware1\!@{{ vcenter.fqdn }} -s /tmp/vsan_silence_{{ item.key }}'
      when: item.value.vsan == true
      with_dict: "{{ clusters }}"

    - name: Delete the temporary Ruby script
      file: path=/tmp/vsan_silence.rb state=absent
      when: 
        - item.value.vsan == true
        - DEBUG_keep_config_files != true
      with_dict: "{{ clusters }}"

    - name: Enable vSAN
      enable_vsan:
        vcenter: "{{ vcenter.ip }}"
        user: "{{ vcenter.user }}"
        passwd: "{{ vcenter.password }}"
        cluster: "{{ item.key }}"
      when: item.value.vsan == True
      with_dict: "{{ clusters }}"

    - name: Claim disks for vSAN
      claim_vsan_disks:
        vcenter: "{{ vcenter.ip }}"
        user: "{{ vcenter.user }}"
        passwd: "{{ vcenter.password }}"
        cluster: "{{ item.key }}"
      when: item.value.vsan == True
      ignore_errors: true
      with_dict: "{{ clusters }}"