##
## Luis has taken ownership of this script
##
## ToDo:
##  1) Need to verify it works against NSX-T v2.5
##
---
- hosts: localhost
  name: createNsxTz.yml
  gather_facts: false
  vars_files:
    - ../config.yml
    - ../software.yml
  tasks:
    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}
                                     Target.Datastore: {{ Target.Datastore }}
                                      Target.VMFolder: {{ Target.VMFolder }}

             Nested_NSXT.Components.LocalManager.FQDN: {{ Nested_NSXT.Components.LocalManager.FQDN }}

              Nested_NSXT.System.Fabric.TransportZone: {{ Nested_NSXT.System.Fabric.TransportZone }}

              Nested_NSXT.System.Fabric.TransportZone: {{ Nested_NSXT.System.Fabric.TransportZone | dict2items }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Create NSX-T transport zones
      nsxt_transport_zones:
        hostname: "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
        username: "{{ Nested_NSXT.Credentials.admin.Name }}"
        password: "{{ Nested_NSXT.Credentials.admin.Password }}"
        validate_certs: False
        resource_type: "TransportZone"
        display_name: "{{ item.key }}"
        description: "{{ item.value.Description }}"
        transport_type: "{{ item.value.Type }}"
        host_switch_name: "{{ item.value.Switch }}"
        host_switch_mode: "STANDARD"
        state: "present"
      register: result
      loop: "{{ Nested_NSXT.System.Fabric.TransportZone | dict2items }}"
      when:
        - Deploy.NSXT.LocalManager == true
