---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Create Uplink segment
      nsxt_policy_segment:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        vlan_ids: "{{ item.vlan_id }}"
        transport_zone_display_name: "{{ item.tz }}"
        state: "present"
      with_items:
        - "{{ segments }}"
      when:
        - deploy_nsxt == true
        - deploy_nsxt_edge == true
