---
- hosts: localhost
  name: createPodConfig.yml
  vars_files:
    - ../software.yml

  vars:
    - PodTemplate: "Pod_Config.j2"
    - PodConfigFile: "Pod-{{ '%03d'|format(Pod.Number|int) }}-Config.yml"

  vars_prompt:

    - name: SourceConfigPath
      prompt: "In which directory is the Pod-Config file you want to have prepared located?"
      unsafe: yes
      private: no
      default: "{{ lookup('env','PWD') }}"

    - name: SourceConfigFile
      prompt: "What is the name of the configuration file that you would like to have prepared?"
      unsafe: yes
      private: no
      default: "config.yml"

  tasks:
    - name: Check to see if the Pod-Config file to be prepared exists
      stat:
        path: "{{ SourceConfigPath }}/{{ SourceConfigFile }}"
      register: ConfigFileCheck


    - name: Display error message if Pod-Config file is not found
      pause:
        seconds: 5
        prompt: |
          *****************************************************************************************************
          ****************************************** ERROR MESSAGE ********************************************
          *****************************************************************************************************

            The provided Pod-Config file could not be found, so this playbook is ending WITHOUT creating any
            output file.  The following provided Pod-Config file could not be found:

                                    {{ SourceConfigPath }}/{{ SourceConfigFile }}

            Please verify the file name provided is correct, and that it is located in the path provided.

          *****************************************************************************************************
      when:
        - ConfigFileCheck.stat.exists != true


    - name: Exit Ansible playbook if Pod-Config file does not exist
      meta: end_play
      when:
        - ConfigFileCheck.stat.exists != true


    - name: Include Pod-Config variables into playbook
      include_vars:
        file: "{{ SourceConfigPath }}/{{ SourceConfigFile }}"


    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                           Pod.Number: {{ Pod.Number }}

                       Pod-Config File Being Prepared: {{ SourceConfigPath }}/{{ SourceConfigFile }}
                               Configuration Template: {{ Target.TemplateFolder }}/{{ PodTemplate }}
                            Target Configuration File: {{ PodConfigFile }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true


    - name: Notify user that this will take some time
      pause:
        seconds: 2
        prompt: |
          =====================================================================================================
          =============================================  NOTICE  ==============================================
          =====================================================================================================

          Generating static configuration file for Pod {{ Pod.Number }}.   Please be patient, as this can take
          some time.  On average, it takes between 5-15 minutes to complete, but this time may vary depending
          on the size of your lab, and the speed of your Ansible Control Station (a.k.a. Ansible Controller).

                The following source file is being prepared: {{ SourceConfigPath }}/{{ SourceConfigFile }}
               Once prepared, it will be saved to this file: {{ lookup('env','HOME') }}/{{ PodConfigFile }}

          Once prepared, you can deploy the Pod using the following command:
                          sudo ansible-playbook -e "@{{ lookup('env','HOME') }}/{{ PodConfigFile }}" deploy.yml

          =====================================================================================================


    - name: Delete existing configuration file
      file:
        path: "{{ lookup('env','HOME') }}/{{ PodConfigFile }}"
        state: absent
      when:
        - Pod.Number is defined
        - Pod.Number >= 10
        - Pod.Number <= 240

    - name: Create variable with current date and time
      set_fact: 
        time: "{{lookup('pipe','date \"+%d-%B-%Y %H:%M\"')}}"
 
    - name: Create Pod Configuration File (Used For Pod Deployment)
      template: 
        src: "{{ Target.TemplateFolder }}/{{ PodTemplate }}"
        dest: "{{ lookup('env','HOME') }}/{{ PodConfigFile }}"
        force: yes
      when: 
        - Pod.Number is defined
        - Pod.Number >= 10
        - Pod.Number <= 240

