## Rutger has ownership of this module
---
- hosts: localhost
  name: createNsxTnp.yml
  gather_facts: false
  vars:
      LOCAL_TransportNodeProfiles_File: "{{ Target.VarsFolder }}/vars_NSXT_TransportNodeProfiles"
  vars_files:
    - ../answerfile.yml
    - ../config.yml
  tasks:
    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================


                                          Ansible Playbook: {{ ansible_play_name }}

                                         Target.Deployment: {{ Target.Deployment }}

                  Nested_NSXT.Components.LocalManager.FQDN: {{ Nested_NSXT.Components.LocalManager.FQDN }}

          Nested_NSXT.System.Fabric.Profile.UplinkProfiles: {{ Nested_NSXT.System.Fabric.Profile.TransportNodeProfiles }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.NSXT.LocalManager == true
  
    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when:        
        - deploy_nsxt == true
        
    - name: Create NSX-T 2.5 transport node profile 
      nsxt_transport_node_profiles:
        hostname: "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
        username: "{{ Nested_NSXT.Credentials.admin.Name }}"
        password: "{{ Nested_NSXT.Credentials.admin.Password }}"
        validate_certs: False
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: Transport Node Profile
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        transport_zone_endpoints:
        - transport_zone_name: "{{ tz_overlay_name }}"
        - transport_zone_name: "{{ tz_vlan_name }}"
        state: present
      with_items:
        - "{{ transport_node_profiles2 }}"
      when:
        - deploy_nsxt == true
        - nsxt_major_version == 2

    - name: Create NSX-T 3.0 transport node profile 
      nsxt_transport_node_profiles:
        hostname: "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
        username: "{{ Nested_NSXT.Credentials.admin.Name }}"
        password: "{{ Nested_NSXT.Credentials.admin.Password }}"
        validate_certs: False
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: Transport Node Profile
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        state: present
      with_items:
        - "{{ transport_node_profiles3 }}"
      when:
        - deploy_nsxt == true
        - nsxt_major_version == 3
