---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  vars_files:
    - ../answerfile.yml
  tasks:

    - name: Conditionally load variables for NSX-T 2.5
      include_vars:
        file: nsxt25.yml
      when: 
        - nsxt_major_version == 2
        - deploy_nsxt == true

    - name: Conditionally load variables for NSX-T 3.0
      include_vars:
        file: nsxt30.yml
      when:
        - nsxt_major_version == 2
        - deploy_nsxt == true
        
    - name: Create NSX-T transport node profile 
      nsxt_transport_node_profiles:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: Transport Node Profile
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        state: present
      with_items:
        - "{{ transport_node_profiles }}"
      when:
        - deploy_nsxt == true
