---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if the NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey

    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: 
        - nsxlicensekey.stat.exists == True      
        - deploy_nsxt == true
        - deploy_nsxt_edge == true

    - name: Deploy and configure NSX-T 2.5 Edge transport nodes
      nsxt_transport_nodes:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description: "Edge transport node"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: present
        transport_zone_endpoints:
        - transport_zone_name: "{{ tz_overlay_name }}"
        - transport_zone_name: "{{ tz_edge_name }}"  
      with_items:
        - "{{ edge_transport_nodes2 }}"
      register: _deploy_edges
      async: 900
      poll: 0
      when: 
        - nsxlicensekey.stat.exists == true
        - deploy_nsxt == true
        - deploy_nsxt_edge == true
        - nsxt_major_version == 2

    - name: Deploy and configure NSX-T 3.0 Edge transport nodes
      nsxt_transport_nodes:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description: "Edge transport node"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: present 
      with_items:
        - "{{ edge_transport_nodes3 }}"
      register: _deploy_edges
      async: 900
      poll: 0
      when: 
        - nsxlicensekey.stat.exists == true
        - deploy_nsxt == true
        - deploy_nsxt_edge == true
        - nsxt_major_version == 3

    - name: Wait 15 minutes for the NSX-T Edge node deployment to finish
      pause: minutes=15
      when: 
        - nsxlicensekey.stat.exists == true
        - deploy_nsxt == true
        - deploy_nsxt_edge == true
        
    - name: Checking if the NSX-T Edge node deployment is finished
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _jobs
      until: _jobs.finished
      delay: 30
      retries: 10      
      with_items: "{{ _deploy_edges.results }}"
      when: 
        - nsxlicensekey.stat.exists == true
        - deploy_nsxt == true
        - deploy_nsxt_edge == true



