---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if the NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey
      when: deploy_nsxt == true

    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: 
        - nsxlicensekey.stat.exists == True        
        - deploy_nsxt == true
        
    - name: Create NSX-T transport node profile 
      nsxt_transport_node_profiles:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: Transport Node Profile
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        transport_zone_endpoints:
        - transport_zone_name: "{{ tz_overlay_name }}"
        - transport_zone_name: "{{ tz_vlan_name }}"
        state: present
      with_items:
        - "{{ transport_node_profiles }}"
      when:
        - deploy_nsxt == true
        - nsxlicensekey.stat.exists == True
