---
- hosts: localhost
  gather_facts: false 
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey

    - name: Create NSX-T Edge cluster
      nsxt_edge_clusters:
          hostname: "{{ nsxman.nsxman01.ip }}"
          username: "{{ nsxmanadminuser }}"
          password: "{{ nsxmanpassword }}"
          validate_certs: False
          display_name: "{{ edge_cluster_name }}"
          cluster_profile_bindings:
          - profile_name: "nsx-default-edge-high-availability-profile"
            resource_type: EdgeHighAvailabilityProfile          
          members:
          - transport_node_name: "{{ edge_node1 }}"
          - transport_node_name: "{{ edge_node2 }}"
          state: present
      when: 
        - nsxlicensekey.stat.exists == true
        - deploy_nsxt == true
        - deploy_nsxt_edge == true
