## Rutger has ownership of this file for the v2 migration ##
---
- hosts: localhost
  name: deployNestedEsxi.yml
  gather_facts: false
  vars_files:
    - ../config.yml
    - ../software.yml
  tasks:
    - name: Display error message if Pod-XXX-Config file is not valid or provided
      pause:
        seconds: 5
        prompt: |
          *****************************************************************************************************
          ****************************************** ERROR MESSAGE ********************************************
          *****************************************************************************************************

            A valid "Pod-XXX-Config.yml" file is required in order for this playbook to run.

            Please verify:
            ==============
              1) You supplied a valid Pod-XXX-Config.yml file via the ansible-playbook -e "@Pod-XXX-Config.yml"
                 command-line option.  Here is an example of a how to load a Pod-XXX-Config.yml file that is
                 located in your home directory:
                                    ansible-playbook -e "@~/Pod-XXX-Config.yml" deploy.yml

              2) The Pod-XXX-Config.yml file provided was created using the playbooks/createPodConfig.yml script.
                 All Pod configuration files used to deploy labs MUST be generated using that script.

              3) You included the proper path with the "-e" option to the Pod-XXX-Config.yml file.

              4) You prefaced the file name in the "-e" option with a '@', as shown in the example above.

          *****************************************************************************************************
      when:
        - Valid_Pod_Config_File is not defined


    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ============================ Display Variables For Pod {{Pod.Number}} ===========================

                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}
                                     Target.Datastore: {{ Target.Datastore }}
                                      Target.VMFolder: {{ Target.VMFolder }}
                                     Target.ISOFolder: {{ Target.ISOFolder }}

                          Target.PortGroup.Trunk.Name: {{ Target.PortGroup.Trunk.Name }}
                       Deploy.Software.ESXi.Installer: {{ Deploy.Software.ESXi.Installer }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Deploy nested ESXi hosts on vCenter
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        name: "{{ item.value.VMName }}"
        state: poweredon
        guest_id: vmkernel65Guest
        cluster: "{{ Target.Cluster }}"
        datacenter: "{{ Target.DataCenter }}"
        folder: "{{ Target.VMFolder }}"
        disk:
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['BootDiskSize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['vSAN']['CacheSize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['vSAN']['CapacitySize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        hardware:
          nested_virt: true
          memory_mb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['Memory'] }}"
          num_cpus: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['CPU'] }}"
          num_cpu_cores_per_socket: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['CoresPerSocket'] }}"
          scsi: paravirtual
        networks:
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
        cdrom:
          type: "iso"
          iso_path: "[{{ Target.Datastore }}] {{ Target.ISOFolder }}/{{ Pod.Number }}{{ item.key }}"
      loop: "{{ Nested_ESXi.Hosts | dict2items }}"
      async: 1800
      poll: 0
      when:
        - Target.Deployment == "vCenter"
        - Nested_Clusters[item.value.Cluster]['DeployHosts'] == true

    - name: Deploy nested ESXi hosts directly onto the ESXi Host
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        name: "{{ item.value.VMName }}"
        state: poweredon
        guest_id: vmkernel65Guest
        esxi_hostname: "{{ Target.FQDN }}"
        folder: "{{ Target.VMFolder }}"
        disk:
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['BootDiskSize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['vSAN']['CapacitySize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        - size_gb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['vSAN']['CacheSize'] }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        hardware:
          nested_virt: true
          memory_mb: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['Memory'] }}"
          num_cpus: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['CPU'] }}"
          num_cpu_cores_per_socket: "{{ Nested_ESXi.HardwareSettings[item.value.Cluster]['CoresPerSocket'] }}"
          scsi: paravirtual
        networks:
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
          - name: "{{ Target.PortGroup.Trunk.Name }}"
            device_type: vmxnet3
        cdrom:
          type: "iso"
          iso_path: "[{{ Target.Datastore }}] {{ Target.ISOFolder }}/{{ Pod.Number }}{{ item.key }}"
      loop: "{{ Nested_ESXi.Hosts | dict2items }}"
      async: 1800
      poll: 0
      when:
        - Target.Deployment == "Host"
        - Nested_Clusters[item.value.Cluster]['DeployHosts'] == true

    - name: Check if the nested ESXi hosts are ready (wait max 15 minutes)
      vmware_guest_info:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        datacenter: "{{ Target.DataCenter }}"
        name: "{{ item.value.VMName }}"
        schema: "vsphere"
      register: vm_facts
      until: vm_facts is search(item.value.vmk.vmk0.Address.IPv4.Address)
      retries: 30
      delay: 30
      loop: "{{ Nested_ESXi.Hosts | dict2items }}"
      when: 
        - Nested_Clusters[item.value.Cluster]['DeployHosts'] == true

    - name: Delete custom ESXi ISO image used for Pod ESXi deployment from the datastore
      vsphere_file:
        host: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        datacenter: "{{ Target.DataCenter }}"
        datastore: "{{ Target.Datastore }}"
        path: "{{ Target.ISOFolder }}/{{ Pod.Number }}{{ item.key }}"
        state: absent
      loop: "{{ Nested_ESXi.Hosts | dict2items }}"
      when: 
        - Nested_Clusters[item.value.Cluster]['DeployHosts'] == true
        - DEBUG.KeepInstallerFiles != true

  tags: nestedESX