---
- hosts: localhost
  name: deployDNS.yml
  gather_facts: false
  vars:
      LOCAL_Ubuntu_Template: "{{ Target.TemplateFolder }}/{{ Deploy.Software.Ubuntu.Template }}"
  tasks:
    - name: Display error message if Pod-XXX-Config file is not valid or provided
      pause:
        seconds: 5
        prompt: |
          *****************************************************************************************************
          ****************************************** ERROR MESSAGE ********************************************
          *****************************************************************************************************

            A valid "Pod-XXX-Config.yml" file is required in order for this playbook to run.

            Please verify:
            ==============
              1) You supplied a valid Pod-XXX-Config.yml file via the ansible-playbook -e "@Pod-XXX-Config.yml"
                 command-line option.  Here is an example of a how to load a Pod-XXX-Config.yml file that is
                 located in your home directory:
                                    ansible-playbook -e "@~/Pod-XXX-Config.yml" deploy.yml

              2) The Pod-XXX-Config.yml file provided was created using the playbooks/createPodConfig.yml script.
                 All Pod configuration files used to deploy labs MUST be generated using that script.

              3) You included the proper path with the "-e" option to the Pod-XXX-Config.yml file.

              4) You prefaced the file name in the "-e" option with a '@', as shown in the example above.

          *****************************************************************************************************
      when:
        - Valid_Pod_Config_File is not defined

    - name: Exit Ansible playbook if Pod-XXX-Config.yml file is not valid or provided
      meta: end_play
      when: Valid_Pod_Config_File is not defined

    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}
                                     Target.Datastore: {{ Target.Datastore }}
                                      Target.VMFolder: {{ Target.VMFolder }}
                                    Target.TempFolder: {{ Target.TempFolder }}

                                       Ubuntu Version: {{ Deploy.Software.Ubuntu.Version }}
                                          Ubuntu FQDN: {{ Nested_DNS.FQDN }}
                                        Ubuntu VMName: {{ Nested_DNS.VM.VMName }}
                                          Ubuntu User: {{ Nested_DNS.OS.Credentials.User }}
                                      Ubuntu Password: {{ {{ Nested_DNS.OS.Credentials.Password }} }}

                                        Ubuntu VM CPU: {{ Nested_DNS.VM.HardwareSettings.CPU }}
                           Ubuntu VM Cores per Socket: {{ Nested_DNS.VM.HardwareSettings.CoresPerSocket }}
                                     Ubuntu VM Memory: {{ Nested_DNS.VM.HardwareSettings.Memory }}
                                  Ubuntu VM Disk Size: {{ Nested_DNS.VM.HardwareSettings.DiskSize }}
                          Ubuntu VM Network PortGroup: {{ Nested_DNS.VM.HardwareSettings.PortGroup }}

                                  Ubuntu IPv4 Address: {{ Nested_DNS.OS.Network.IPv4.Address }}
                               Ubuntu Network Netmask: {{ (Nested_DNS.OS.Network.IPv4.Address + '/' + Nested_DNS.OS.Network.IPv4.Prefix) | ipaddr('netmask') }}
                          Ubuntu Network IPv4 Gateway: {{ Nested_DNS.OS.Network.IPv4.Gateway }}

                                    Ubuntu Media Path: {{ Deploy.Software.Ubuntu.Directory }}
                                    Ubuntu Media File: {{ Deploy.Software.Ubuntu.File }}


          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Check if the Ubuntu VM is already deployed
      vmware_guest_info:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        datacenter: "{{ Target.DataCenter }}"
        folder: "{{ Target.VMFolder }}"
        name: "{{ Nested_DNS.VM.VMName }}"
        schema: "vsphere"
        properties: ["overallStatus"]
      register: ubuntu_status
      ignore_errors: true
      no_log: true
      when:
        - Deploy.DNS == true

    - name: Read the structure from template into a variable
      set_fact:
        var_UbuntuConfiguration: "{{ lookup('template', LOCAL_Ubuntu_Template) | from_yaml }}"
      when:
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display var_UbuntuConfiguration Variable ===================================

              var_UbuntuConfiguration: {{ var_UbuntuConfiguration | to_nice_yaml(indent=2) }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - var_UbuntuConfiguration != ""
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: Create temp directory
      file:
        path: "{{ Target.TempFolder }}"
        state: directory
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
    

    - name: Check if Ubuntu ISO file exists locally exists locally in the software repository
      stat:
        path: "{{ Deploy.Software.Ubuntu.Directory }}/{{ Deploy.Software.Ubuntu.File }}"
      register: InstallerFileCheck
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Update Ubuntu ISO file in the local software repository (overwrite if exists)
      get_url:
        url:  "{{ Deploy.Software.Ubuntu.URL }}/{{ Deploy.Software.Ubuntu.File }}"
        dest: "{{ Deploy.Software.Ubuntu.Directory }}/{{ Deploy.Software.Ubuntu.File }}"
        force: yes
      when: 
        - (InstallerFileCheck.stat.exists != true) or (Deploy.Software.Options.UseLocalInstaller != true)
        - Deploy.Software.Options.KeepNewInstallers == true
        - ubuntu_status is failed
        - Deploy.DNS == true 
        
    - name: Mount Ubuntu ISO file
      action: mount name="{{ Target.ISOMount }}" src="{{ Deploy.Software.Ubuntu.Directory }}/{{ Deploy.Software.Ubuntu.File }}" opts=loop fstype=iso9660 state=mounted
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Copy Ubuntu ISO file contents
      copy: 
        src: "{{ Target.ISOMount }}/"
        dest: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}/"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Unmount Ubuntu ISO
      action: mount name="{{ Target.ISOMount }}" src="{{ Deploy.Software.Ubuntu.Directory }}/{{ Deploy.Software.Ubuntu.File }}" fstype=iso9660 state=absent
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Edit txt.cfg to enable autoinstaller 
      replace:
        dest: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}/isolinux/txt.cfg"
        regexp: 'append   initrd=/casper/initrd quiet  ---'
        replace: 'append   initrd=/casper/initrd quiet --- autoinstall ds=nocloud;s=/cdrom/{{ Common.DNS.Domain }}/'
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Create directory to store user-data and meta-data
      file:
        path: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}/{{ Common.DNS.Domain }}"
        state: directory
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Create autoinstaller files
      template: 
        src: "{{ item.Source }}"
        dest: "{{ item.FinalDestination }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Templates.AutoInstall }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Create custom Ubuntu ISO
      command: "xorrisofs -relaxed-filenames -J -R -o {{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.File }} -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table {{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}/"
      args:
        chdir: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}/"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Upload the custom Ubuntu ISO to the datastore
      vsphere_copy: 
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        datacenter: "{{ Target.DataCenter }}"
        src: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.File }}" 
        datastore: "{{ Target.Datastore }}"
        path: "{{ Target.ISOFolder }}/{{ Deploy.Software.Ubuntu.File }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true  

    - name: Deploy Ubuntu VM
      vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_DNS.VM.VMName }}"
        state: poweredon
        guest_id: ubuntu64Guest
        cluster: "{{ Target.Cluster }}"
        datacenter: "{{ Target.DataCenter }}"
        folder: "{{ Target.VMFolder }}"
        disk:
        - size_gb: "{{ Nested_DNS.VM.HardwareSettings.DiskSize }}"
          type: "{{ Common.DiskProvisioning }}"
          datastore: "{{ Target.Datastore }}"
        hardware:
          memory_mb: "{{ Nested_DNS.VM.HardwareSettings.Memory }}"
          num_cpus: "{{ Nested_DNS.VM.HardwareSettings.CPU }}"
          num_cpu_cores_per_socket: "{{ Nested_DNS.VM.HardwareSettings.CoresPerSocket }}"
          scsi: paravirtual
        networks:
          - name: "{{ Nested_DNS.VM.HardwareSettings.PortGroup }}"
            device_type: vmxnet3
        cdrom:
          type: "iso"
          iso_path: "[{{ Target.Datastore }}] {{ Target.ISOFolder }}/{{ Deploy.Software.Ubuntu.File }}"
        annotation: | 
                    {{ Common.Annotation }}
                    Username: {{ Nested_DNS.OS.Credentials.User }}
                    Password: {{ Nested_DNS.OS.Credentials.Password }}
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: Wait 15 minutes for the Ubuntu installation to complete
      pause:
        seconds: 900
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: Set password for the Ubuntu user
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: VMware1!
        vm_shell: /usr/bin/echo
        vm_shell_args: "'{{ Nested_DNS.OS.Credentials.User }}:{{ Nested_DNS.OS.Credentials.Password }}' | sudo chpasswd"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: Create configuration files
      template: 
        src: "{{ item.Source }}"
        dest: "{{ item.LocalDestination }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Templates.AfterBoot }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Templates.AfterBoot != ""

    - name: Copy configuration files to the Ubuntu VM
      vmware_guest_file_operation:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        copy:
          src: "{{ item.LocalDestination }}"
          dest: "{{ item.StageDestination }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Templates.AfterBoot }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Templates.AfterBoot != ""

    - name: Move configuration files to their final location on the Ubuntu VM
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        vm_shell: /usr/bin/sudo
        vm_shell_args: "mv {{ item.StageDestination }} {{ item.FinalDestination }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Templates.AfterBoot }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Templates.AfterBoot != ""

    - name: Create directories on Ubuntu VM
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        vm_shell: /usr/bin/sudo
        vm_shell_args: "mkdir {{ item.Path }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Directories }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Directories != ""

    - name: Set owner on directories on Ubuntu VM
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        vm_shell: /usr/bin/sudo
        vm_shell_args: "chown {{ item.Owner }} {{ item.Path }} "
      loop: "{{ var_UbuntuConfiguration.Configuration.Directories }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Directories != ""

    - name: Apply the network configuration on Ubuntu VM
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        vm_shell: /usr/bin/sudo
        vm_shell_args: "netplan apply"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true

    - name: Restart daemons on Ubuntu VM
      vmware_vm_shell:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        vm_id: "{{ Nested_DNS.VM.VMName }}"
        vm_username: "{{ Nested_DNS.OS.Credentials.User }}"
        vm_password: "{{ Nested_DNS.OS.Credentials.Password }}"
        vm_shell: /usr/bin/sudo
        vm_shell_args: "systemctl restart {{ item.Daemon }}"
      loop: "{{ var_UbuntuConfiguration.Configuration.Packages }}"
      when: 
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Packages != ""

    - name: Delete local ISO content directory
      file:
        path: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.Installer }}"
        state: absent
      when: 
        - DEBUG.KeepInstallerFiles != true
        - Deploy.DNS == true
        - ubuntu_status is failed

    - name: Delete the custom Ubuntu ISO file
      file:
        path: "{{ Target.TempFolder }}/{{ Deploy.Software.Ubuntu.File }}" 
        state: absent
      when: 
        - DEBUG.KeepInstallerFiles != true
        - Deploy.DNS == true
        - ubuntu_status is failed

    - name: Delete configuration files
      file:
        path: "{{ item.LocalDestination }}"
        state: absent
      loop: "{{ var_UbuntuConfiguration.Configuration.Templates.AfterBoot }}"
      when: 
        - DEBUG.KeepConfigFiles != true
        - ubuntu_status is failed
        - Deploy.DNS == true
        - var_UbuntuConfiguration.Configuration.Templates.AfterBoot != ""
