## Luis has ownership of this file for the v2 migration ##
#
# ToDo:
#  1) Use API to disable password expiration for admin.  Documented here: https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.0/installation/GUID-89E9BD91-6FD4-481A-A76F-7A20DB5B916C.html
#
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../software.yml
    - ../config.yml
  tasks:
    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ '%03d'|format(Pod.Number|int) }} ==================================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}
                                     Target.Datastore: {{ Target.Datastore }}
                                      Target.VMFolder: {{ Target.VMFolder }}

                                           NSX-T Role: {{ Nested_NSXT.Components.LocalManager.Deployment.Role }}
                                        NSX-T Version: {{ Deploy.Software.NSXT.Version }}
                                   NSX-T Manager FQDN: {{ Nested_NSXT.Components.LocalManager.FQDN }}
                                         NSX-T VMName: {{ Nested_NSXT.Components.LocalManager.VMName }}


                                                OVF Variables
                                                =============

                                         NSX-T VMName: {{ Nested_NSXT.Components.LocalManager.VMName }}
                                           NSX-T Size: {{ Nested_NSXT.Components.LocalManager.Deployment.Size  }}
                                    Network PortGroup: {{ Target.PortGroup.Management.Name }}

                                           Audit User: {{ Nested_NSXT.Components.LocalManager.User.audit.Name }}
                                       Audit Password: {{ Nested_NSXT.Components.LocalManager.User.audit.Password }}

                                             CLI User: {{ Nested_NSXT.Components.LocalManager.User.admin.Name }}
                                         CLI Password: {{ Nested_NSXT.Components.LocalManager.User.root.Password }}

                                 Network IPv4 Address: {{ Nested_NSXT.Components.LocalManager.Address.IPv4.Address }}
                                      Network Netmask: {{ (Nested_NSXT.Components.LocalManager.Address.IPv4.Address + '/' + Nested_NSXT.Components.LocalManager.Address.IPv4.Prefix) | ipaddr('netmask') }}
                                      Network Gateway: {{ Nested_NSXT.Components.LocalManager.Address.IPv4.Gateway }}

                                   Network NTP Server: {{ Common.NTP.Server1.IPv4 }}
                                   Network DNS Server: {{ Common.DNS.Server1.IPv4 }}
                                   Network DNS Domain: {{ Common.DNS.Domain }}

                                     NSX-T Media Path: {{ Software[Deploy.Software.NSXT.Vendor][Deploy.Software.NSXT.Product]['Installers'][Deploy.Software.NSXT.Version]['Location'].Local }}
                                     NSX-T Media File: {{ Software[Deploy.Software.NSXT.Vendor][Deploy.Software.NSXT.Product]['Installers'][Deploy.Software.NSXT.Version].File }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Check if NSX-T Local Manager is already installed
      uri:
        url: https://{{ Nested_NSXT.Components.LocalManager.FQDN }}
        validate_certs: False
        timeout: 5
      register: nsxman_check
      ignore_errors: true
      failed_when: false
      no_log: true
      when: Deploy.NSXT.LocalManager == true

    - name: Deploy NSX-T Local Manager from OVA
      vmware_deploy_ovf:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        datastore: "{{ Target.Datastore }}"
        allow_duplicates: no
        folder: "{{ Target.VMFolder }}"
        datacenter: "{{ Target.DataCenter }}"
        cluster: "{{ Target.Cluster }}"
        name: "{{ Nested_NSXT.Components.LocalManager.VMName }}"
        ovf:  "{{ Software[Deploy.Software.NSXT.Vendor][Deploy.Software.NSXT.Product]['Installers'][Deploy.Software.NSXT.Version]['Location'].Local }}/{{ Software[Deploy.Software.NSXT.Vendor][Deploy.Software.NSXT.Product]['Installers'][Deploy.Software.NSXT.Version].File }}"
        deployment_option: "{{ Nested_NSXT.Components.LocalManager.Deployment.Size }}"
        networks:
          "Network 1": "{{ Target.PortGroup.Management.Name }}"
        disk_provisioning: "{{ Common.DiskProvisioning }}"
        power_on: yes
        fail_on_spec_warnings: yes
        wait: yes
        wait_for_ip_address: yes
        inject_ovf_env: yes
        properties:
          nsx_cli_audit_username: "{{ Nested_NSXT.Components.LocalManager.User.audit.Name }}"
          nsx_cli_audit_passwd_0: "{{ Nested_NSXT.Components.LocalManager.User.audit.Password }}"
          nsx_cli_username: "{{ Nested_NSXT.Components.LocalManager.User.admin.Name }}"
          nsx_cli_passwd_0: "{{ Nested_NSXT.Components.LocalManager.User.admin.Password }}"
          nsx_allowSSHRootLogin: "{{ Nested_NSXT.Components.LocalManager.Deployment.EnableSSH }}"
          nsx_isSSHEnabled: "{{ Nested_NSXT.Components.LocalManager.Deployment.EnableSSH }}"
          nsx_dns1_0: "{{ Common.DNS.Server1.IPv4 }}"
          nsx_domain_0: "{{ Common.DNS.Domain }}"
          nsx_gateway_0: "{{ Nested_NSXT.Components.LocalManager.Address.IPv4.Gateway }}"
          nsx_hostname:  "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
          nsx_ip_0:      "{{ Nested_NSXT.Components.LocalManager.Address.IPv4.Address }}"
          nsx_netmask_0: "{{ (Nested_NSXT.Components.LocalManager.Address.IPv4.Address + '/' + Nested_NSXT.Components.LocalManager.Address.IPv4.Prefix) | ipaddr('netmask') }}"
          nsx_ntp_0:     "{{ Common.NTP.Server1.IPv4 }}"
          nsx_passwd_0:  "{{ Nested_NSXT.Components.LocalManager.User.admin.Password }}"
          nsx_role:      "{{ Nested_NSXT.Components.LocalManager.Deployment.Role }}"
      delegate_to: localhost
      when:
        - Deploy.NSXT.LocalManager == true
        - nsxman_check.status != 200
      async: 7200
      poll: 0
      register: deployment

    - name: Wait 3 seconds before start checking whether the NSX-T Manager node is ready
      pause: seconds=3
      when: 
        - Deploy.NSXT.LocalManager == true
        - deployment.changed == true

    - name: Result check for NSX-T Manager node deployment
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      with_items: "{{ deployment.results }}"
      when:
        - Deploy.NSXT.LocalManager == true
        - deployment.changed == true
        - item.started is defined

    - name: Wait until the NSX-T API reports that the manager cluster is "STABLE" (wait max 60 minutes)
      uri:
        url: https://{{ Nested_NSXT.Components.LocalManager.FQDN | lower }}/api/v1/cluster/status
        validate_certs: no
        timeout: 5
        force_basic_auth: yes
        url_username: "{{ Nested_NSXT.Components.LocalManager.User.admin.Name }}"
        url_password: "{{ Nested_NSXT.Components.LocalManager.User.admin.Password }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      register: result
      until: result.status == 200 and result.json.detailed_cluster_status.overall_status == "STABLE"
      retries: 120
      delay: 30
      when: 
        - Deploy.NSXT.LocalManager == true
