### Luis will take owneship of this playbook
##
## While we are converting from v1 to v2, we need to create vSwitches for Both environments
##    v1 Environment does not force 3 digits Pod numbers
##    v2 Environment does force 3 digit Pod numbers
##
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../config.yml
    - ../licenses.yml
    - ../software.yml
    - ../answerfile.yml
  tasks:
##
## version 2
##
    - name: Create a VMware vSwitch on the ESXi host for the lab environment
      vmware_vswitch:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        mtu: 9000


    - name: Create a management port group for the lab environment
      vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False        
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.VLAN }}"
        vlan_id: "{{ Target.PortGroup.VLANID }}"
        network_policy:
          promiscuous_mode: True


    - name: Create trunk port group for the lab environment
      vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: False
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.Trunk }}"
        vlan_id: "4095"
        network_policy:
          promiscuous_mode: True
          forged_transmits: True
          mac_changes: True
          

    - name: Wait 5 seconds for the port groups to become available
      pause: seconds=5



##
## Version 1 -- This can be deleted once full conversion is complete
##
    - name: Create a VMware vSwitch on the ESXi host for the lab environment
      vmware_vswitch:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        mtu: 9000


    - name: Create a management port group for the lab environment
      vmware_portgroup:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False        
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.vlanpg }}"
        vlan_id: "{{ physicalESX.vlan }}"
        network_policy:
          promiscuous_mode: True


    - name: Create trunk port group for the lab environment
      vmware_portgroup:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.trunkpg }}"
        vlan_id: "4095"
        network_policy:
          promiscuous_mode: True
          forged_transmits: True
          mac_changes: True
          

    - name: Wait 5 seconds for the port groups to become available
      pause: seconds=5
