---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../config.yml
  tasks:
    - name: Register NSX-T Compute Manager
      nsxt_fabric_compute_managers:
          hostname: "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
          username: "{{ Nested_NSXT.Credentials.admin.Name }}"
          password: "{{ Nested_NSXT.Credentials.admin.Password }}"
          validate_certs: False
          display_name: "{{ Nested_vCenter.VMName }}"                 # Using VMName as no need for full domain
          server: "{{ Nested_vCenter.FQDN }}"
          origin_type: vCenter
          credential:
            credential_type: UsernamePasswordLoginCredential
            username: "{{ Nested_vCenter.User }}"
            password: "{{ Nested_vCenter.Password }}"
          state: present
      when: Deploy.NSXT.LocalManager == true


###
### Original Task (Keep until updated on is working)
###
#
#    - name: Register NSX-T Compute Manager
#      nsxt_fabric_compute_managers:
#          hostname: "{{ nsxman.nsxman01.ip }}"
#          username: "{{ nsxmanadminuser }}"
#          password: "{{ nsxmanpassword }}"
#          validate_certs: False
#          display_name: "{{ vcenter.fqdn }}"
#          server: "{{ vcenter.fqdn }}"
#          origin_type: vCenter
#          credential:
#            credential_type: UsernamePasswordLoginCredential
#            username: "{{ vcenter.user }}"
#            password: "{{ vcenter.password }}"
#          state: present
#      when: deploy_nsxt == true
