---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:

    - name: Create rb script
      template: 
        src=../templates/vsan_silence.rb
        dest=/tmp/vsan_silence.rb

    - name: Copy rb script to vCenter
      vmware_guest_file_operation:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        vm_id: "{{ vcenter.vmname }}"
        vm_username: "root"
        vm_password: "{{ vcenter.password }}"
        copy:
            src: "/tmp/vsan_silence.rb"
            dest: "/tmp/vsan_silence.rb"
            overwrite: true
    - name: Run rb script
      vmware_vm_shell:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: false
        vm_id: "{{ vcenter.vmname }}"
        vm_username: "root"
        vm_password: "{{ vcenter.password }}"
        vm_shell: /usr/bin/rb
        vm_shell_args: '{{ vcenter.user }}:VMware1\!@{{ vcenter.fqdn }} -s /tmp/vsan_silence.rb'

    - name: Delete the temporary rb script
      file: path=/tmp/vsan_silence.rb state=absent
      when: 
        - DEBUG_keep_config_files != true