- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:

    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: deploy_nsxt == true

    - name: List transport node profiles
      nsxt_transport_node_profiles_facts:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
      check_mode: yes
