## Luis has ownership of this file for the v2 migration ##
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../software.yml
    - ../config.yml
  tasks:
    - name: DEBUG -- Display Target Variables (Pause)
      pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          =================================== DEBUG: Display Variables ====================================

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.vSwitch: {{ Target.vSwitch }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}

                               Software RootDirectory: {{ RootDirectory }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true


    - name: Loop through Software repository file, creating all local directories
      debug: msg: "{{ item }}"
      with_dict: {{ Software|flatten(levels=5) }}



#    - name: Delete the temporary template file for VyOS router
#      file: 
#        path: "{{ Target.TempFolder }}/{{ Deploy.Software.Router.Config }}"
#        state: directory
#        mode: "0666"
#      when: 
#        - Deploy.Router == true
#        - status is failed
#        - DEBUG.KeepConfigFiles != true



